#!/usr/bin/env node

const fs = require("node:fs");
const path = require("node:path");

const versions = {
  php: "^8.2",
  laravel: "^12.0",
  tinker: "^2.10",
  faker: "^1.24",
  pint: "^1.29",
  sail: "^1.57",
  mockery: "^1.6",
  collision: "^8.6",
  phpunit: "^11.5",
  axios: "^1.15.2",
  concurrently: "^9.2.1",
  laravelVitePlugin: "^3.0.1",
  tailwindcss: "^4.2.4",
  tailwindcssVite: "^4.2.4",
  vite: "^8.0.10",
};

function main() {
  const { target: parsedTarget, force, help } = parseArgs(process.argv.slice(2));

  if (help) {
    printHelp();
    return;
  }

  const target = parsedTarget || ".";
  const targetDir = path.resolve(process.cwd(), target);
  const projectName = packageNameFromTarget(targetDir, target);
  createProject(targetDir, projectName, force);

  const relativeTarget = path.relative(process.cwd(), targetDir) || ".";
  console.log("");
  console.log("Created Laravel framework template in " + relativeTarget);
  console.log("");
  console.log("Next steps:");
  if (relativeTarget !== ".") {
    console.log("  cd " + relativeTarget);
  }
  console.log("  composer install");
  console.log("  php artisan key:generate");
  console.log("  npm install");
  console.log("  npm run build");
  console.log("  php artisan migrate");
  console.log("  composer run dev");
}

function parseArgs(args) {
  let target = "";
  let force = false;
  let help = false;

  for (const arg of args) {
    if (arg === "-h" || arg === "--help") {
      help = true;
    } else if (arg === "-f" || arg === "--force") {
      force = true;
    } else if (arg.startsWith("-")) {
      throw new Error("Unknown option: " + arg);
    } else if (!target) {
      target = arg;
    }
  }

  return { target, force, help };
}

function printHelp() {
  console.log(`
laravel-template-jpz

Usage:
  laravel-template-jpz
  laravel-template-jpz [project-name]
  laravel-template-jpz . --force

Examples:
  laravel-template-jpz
  laravel-template-jpz my-app

Options:
  -f, --force   Allow scaffolding into a non-empty directory
  -h, --help    Show this help message

No project name means the template will be created in the current directory.
`);
}

function packageNameFromTarget(targetDir, rawTarget) {
  const folderName = rawTarget === "." ? path.basename(targetDir) : path.basename(rawTarget);
  const cleaned = folderName
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^[._-]+|[._-]+$/g, "");

  return cleaned || "laravel-app";
}

function createProject(targetDir, projectName, force) {
  ensureSafeTarget(targetDir, force);

  const template = buildTemplate(projectName);

  for (const directory of template.directories) {
    fs.mkdirSync(path.join(targetDir, directory), { recursive: true });
  }

  for (const [filePath, contents] of Object.entries(template.files)) {
    const destination = path.join(targetDir, filePath);
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, contents, "utf8");
  }
}

function ensureSafeTarget(targetDir, force) {
  if (!fs.existsSync(targetDir)) {
    fs.mkdirSync(targetDir, { recursive: true });
    return;
  }

  const existingFiles = fs.readdirSync(targetDir);
  if (existingFiles.length > 0 && !force) {
    throw new Error(
      "Target directory is not empty. Use --force to scaffold into it: " + targetDir
    );
  }
}

function buildTemplate(projectName) {
  const appTitle = toTitle(projectName);
  const composerName = "app/" + projectName;

  const directories = [
    "app/Http/Controllers",
    "app/Http/Middleware",
    "app/Http/Requests",
    "app/Models",
    "app/Providers",
    "app/Services",
    "bootstrap/cache",
    "config",
    "database/factories",
    "database/migrations",
    "database/seeders",
    "public",
    "resources/css",
    "resources/js",
    "resources/views/components/layouts",
    "resources/views/pages",
    "routes",
    "storage/app/public",
    "storage/framework/cache/data",
    "storage/framework/sessions",
    "storage/framework/testing",
    "storage/framework/views",
    "storage/logs",
    "tests/Feature",
    "tests/Unit",
  ];

  const files = {
    ".editorconfig": lines([
      "root = true",
      "",
      "[*]",
      "charset = utf-8",
      "end_of_line = lf",
      "insert_final_newline = true",
      "indent_style = space",
      "indent_size = 4",
      "trim_trailing_whitespace = true",
      "",
      "[*.md]",
      "trim_trailing_whitespace = false",
      "",
      "[*.{yml,yaml,json,js,css,blade.php}]",
      "indent_size = 2",
    ]),
    ".env.example": lines([
      "APP_NAME=" + envString(appTitle),
      "APP_ENV=local",
      "APP_KEY=",
      "APP_DEBUG=true",
      "APP_URL=http://localhost",
      "",
      "APP_LOCALE=en",
      "APP_FALLBACK_LOCALE=en",
      "APP_FAKER_LOCALE=en_US",
      "",
      "APP_MAINTENANCE_DRIVER=file",
      "",
      "PHP_CLI_SERVER_WORKERS=4",
      "",
      "BCRYPT_ROUNDS=12",
      "",
      "LOG_CHANNEL=stack",
      "LOG_STACK=single",
      "LOG_DEPRECATIONS_CHANNEL=null",
      "LOG_LEVEL=debug",
      "",
      "DB_CONNECTION=sqlite",
      "# DB_HOST=127.0.0.1",
      "# DB_PORT=3306",
      "# DB_DATABASE=laravel",
      "# DB_USERNAME=root",
      "# DB_PASSWORD=",
      "",
      "SESSION_DRIVER=database",
      "SESSION_LIFETIME=120",
      "SESSION_ENCRYPT=false",
      "SESSION_PATH=/",
      "SESSION_DOMAIN=null",
      "",
      "BROADCAST_CONNECTION=log",
      "FILESYSTEM_DISK=local",
      "QUEUE_CONNECTION=database",
      "",
      "CACHE_STORE=database",
      "CACHE_PREFIX=",
      "",
      "MAIL_MAILER=log",
      "MAIL_SCHEME=null",
      "MAIL_HOST=127.0.0.1",
      "MAIL_PORT=2525",
      "MAIL_USERNAME=null",
      "MAIL_PASSWORD=null",
      "MAIL_FROM_ADDRESS=\"hello@example.com\"",
      "MAIL_FROM_NAME=\"${APP_NAME}\"",
      "",
      "VITE_APP_NAME=\"${APP_NAME}\"",
    ]),
    ".gitattributes": lines([
      "* text=auto eol=lf",
      "",
      "*.blade.php diff=html",
      "*.css diff=css",
      "*.html diff=html",
      "*.md diff=markdown",
      "*.php diff=php",
    ]),
    ".gitignore": lines([
      "/node_modules",
      "/public/build",
      "/public/hot",
      "/public/storage",
      "/storage/*.key",
      "/vendor",
      ".env",
      ".env.backup",
      ".env.production",
      ".phpunit.result.cache",
      "Homestead.json",
      "Homestead.yaml",
      "auth.json",
      "npm-debug.log",
      "yarn-error.log",
      "pnpm-debug.log",
      ".DS_Store",
      "/.fleet",
      "/.idea",
      "/.vscode",
    ]),
    "README.md": lines([
      "# " + appTitle,
      "",
      "Laravel framework template generated with Blade, Vite, Tailwind CSS, SQLite defaults, and a health-check API.",
      "",
      "## Getting Started",
      "",
      "Install PHP dependencies:",
      "",
      "```bash",
      "composer install",
      "```",
      "",
      "Generate the app key:",
      "",
      "```bash",
      "php artisan key:generate",
      "```",
      "",
      "Install and build frontend assets:",
      "",
      "```bash",
      "npm install",
      "npm run build",
      "```",
      "",
      "Run the database migrations:",
      "",
      "```bash",
      "php artisan migrate",
      "```",
      "",
      "Start the local development server:",
      "",
      "```bash",
      "composer run dev",
      "```",
      "",
      "The app runs on `http://localhost:8000` by default.",
      "",
      "## Health Check",
      "",
      "```text",
      "GET /api/health",
      "```",
      "",
      "Run tests with:",
      "",
      "```bash",
      "php artisan test",
      "```",
    ]),
    "artisan": lines([
      "#!/usr/bin/env php",
      "<?php",
      "",
      "use Illuminate\\Foundation\\Application;",
      "use Symfony\\Component\\Console\\Input\\ArgvInput;",
      "",
      "define('LARAVEL_START', microtime(true));",
      "",
      "require __DIR__.'/vendor/autoload.php';",
      "",
      "/** @var Application $app */",
      "$app = require_once __DIR__.'/bootstrap/app.php';",
      "",
      "$status = $app->handleCommand(new ArgvInput);",
      "",
      "exit($status);",
    ]),
    "composer.json": json({
      name: composerName,
      type: "project",
      description: "A Laravel framework template generated by laravel-template-jpz.",
      keywords: ["laravel", "framework", "starter"],
      license: "MIT",
      require: {
        php: versions.php,
        "laravel/framework": versions.laravel,
        "laravel/tinker": versions.tinker,
      },
      "require-dev": {
        "fakerphp/faker": versions.faker,
        "laravel/pint": versions.pint,
        "laravel/sail": versions.sail,
        "mockery/mockery": versions.mockery,
        "nunomaduro/collision": versions.collision,
        "phpunit/phpunit": versions.phpunit,
      },
      autoload: {
        "psr-4": {
          "App\\": "app/",
          "Database\\Factories\\": "database/factories/",
          "Database\\Seeders\\": "database/seeders/",
        },
      },
      "autoload-dev": {
        "psr-4": {
          "Tests\\": "tests/",
        },
      },
      scripts: {
        "post-autoload-dump": [
          "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
          "@php artisan package:discover --ansi",
        ],
        "post-update-cmd": [
          "@php artisan vendor:publish --tag=laravel-assets --ansi --force",
        ],
        "post-root-package-install": [
          "@php -r \"file_exists('.env') || copy('.env.example', '.env');\"",
        ],
        "post-create-project-cmd": [
          "@php artisan key:generate --ansi",
          "@php artisan migrate --ansi",
        ],
        dev: [
          "Composer\\Config::disableProcessTimeout",
          "npx concurrently -c \"#93c5fd,#c4b5fd,#fdba74\" \"php artisan serve\" \"php artisan queue:listen --tries=1\" \"npm run dev\" --names=server,queue,vite",
        ],
        test: [
          "@php artisan config:clear --ansi",
          "@php artisan test",
        ],
      },
      extra: {
        laravel: {
          "dont-discover": [],
        },
      },
      config: {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {},
      },
      "minimum-stability": "stable",
      "prefer-stable": true,
    }),
    "package.json": json({
      private: true,
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
      },
      devDependencies: {
        "@tailwindcss/vite": versions.tailwindcssVite,
        axios: versions.axios,
        concurrently: versions.concurrently,
        "laravel-vite-plugin": versions.laravelVitePlugin,
        tailwindcss: versions.tailwindcss,
        vite: versions.vite,
      },
    }),
    "phpunit.xml": lines([
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
      "<phpunit xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"",
      "         xsi:noNamespaceSchemaLocation=\"vendor/phpunit/phpunit/phpunit.xsd\"",
      "         bootstrap=\"vendor/autoload.php\"",
      "         colors=\"true\">",
      "  <testsuites>",
      "    <testsuite name=\"Unit\">",
      "      <directory>tests/Unit</directory>",
      "    </testsuite>",
      "    <testsuite name=\"Feature\">",
      "      <directory>tests/Feature</directory>",
      "    </testsuite>",
      "  </testsuites>",
      "  <source>",
      "    <include>",
      "      <directory>app</directory>",
      "    </include>",
      "  </source>",
      "  <php>",
      "    <env name=\"APP_ENV\" value=\"testing\"/>",
      "    <env name=\"APP_MAINTENANCE_DRIVER\" value=\"file\"/>",
      "    <env name=\"BCRYPT_ROUNDS\" value=\"4\"/>",
      "    <env name=\"CACHE_STORE\" value=\"array\"/>",
      "    <env name=\"DB_CONNECTION\" value=\"sqlite\"/>",
      "    <env name=\"DB_DATABASE\" value=\":memory:\"/>",
      "    <env name=\"MAIL_MAILER\" value=\"array\"/>",
      "    <env name=\"QUEUE_CONNECTION\" value=\"sync\"/>",
      "    <env name=\"SESSION_DRIVER\" value=\"array\"/>",
      "  </php>",
      "</phpunit>",
    ]),
    "vite.config.js": lines([
      "import tailwindcss from '@tailwindcss/vite';",
      "import laravel from 'laravel-vite-plugin';",
      "import { defineConfig } from 'vite';",
      "",
      "export default defineConfig({",
      "  plugins: [",
      "    laravel({",
      "      input: ['resources/css/app.css', 'resources/js/app.js'],",
      "      refresh: true,",
      "    }),",
      "    tailwindcss(),",
      "  ],",
      "});",
    ]),
    "app/Http/Controllers/Controller.php": lines([
      "<?php",
      "",
      "namespace App\\Http\\Controllers;",
      "",
      "abstract class Controller",
      "{",
      "    //",
      "}",
    ]),
    "app/Http/Controllers/HealthController.php": lines([
      "<?php",
      "",
      "namespace App\\Http\\Controllers;",
      "",
      "use App\\Services\\HealthService;",
      "use Illuminate\\Http\\JsonResponse;",
      "",
      "class HealthController extends Controller",
      "{",
      "    public function __invoke(HealthService $health): JsonResponse",
      "    {",
      "        return response()->json($health->status());",
      "    }",
      "}",
    ]),
    "app/Http/Middleware/.gitkeep": "",
    "app/Http/Requests/.gitkeep": "",
    "app/Models/User.php": lines([
      "<?php",
      "",
      "namespace App\\Models;",
      "",
      "use Illuminate\\Database\\Eloquent\\Factories\\HasFactory;",
      "use Illuminate\\Foundation\\Auth\\User as Authenticatable;",
      "use Illuminate\\Notifications\\Notifiable;",
      "",
      "class User extends Authenticatable",
      "{",
      "    /** @use HasFactory<\\Database\\Factories\\UserFactory> */",
      "    use HasFactory, Notifiable;",
      "",
      "    /**",
      "     * The attributes that are mass assignable.",
      "     *",
      "     * @var list<string>",
      "     */",
      "    protected $fillable = [",
      "        'name',",
      "        'email',",
      "        'password',",
      "    ];",
      "",
      "    /**",
      "     * The attributes that should be hidden for serialization.",
      "     *",
      "     * @var list<string>",
      "     */",
      "    protected $hidden = [",
      "        'password',",
      "        'remember_token',",
      "    ];",
      "",
      "    /**",
      "     * Get the attributes that should be cast.",
      "     *",
      "     * @return array<string, string>",
      "     */",
      "    protected function casts(): array",
      "    {",
      "        return [",
      "            'email_verified_at' => 'datetime',",
      "            'password' => 'hashed',",
      "        ];",
      "    }",
      "}",
    ]),
    "app/Providers/AppServiceProvider.php": lines([
      "<?php",
      "",
      "namespace App\\Providers;",
      "",
      "use Illuminate\\Database\\Eloquent\\Model;",
      "use Illuminate\\Support\\ServiceProvider;",
      "",
      "class AppServiceProvider extends ServiceProvider",
      "{",
      "    public function register(): void",
      "    {",
      "        //",
      "    }",
      "",
      "    public function boot(): void",
      "    {",
      "        Model::shouldBeStrict(! $this->app->isProduction());",
      "    }",
      "}",
    ]),
    "app/Services/HealthService.php": lines([
      "<?php",
      "",
      "namespace App\\Services;",
      "",
      "class HealthService",
      "{",
      "    /**",
      "     * @return array<string, string>",
      "     */",
      "    public function status(): array",
      "    {",
      "        return [",
      "            'status' => 'ok',",
      "            'service' => config('app.name'),",
      "            'environment' => app()->environment(),",
      "            'timestamp' => now()->toISOString(),",
      "        ];",
      "    }",
      "}",
    ]),
    "bootstrap/app.php": lines([
      "<?php",
      "",
      "use Illuminate\\Foundation\\Application;",
      "use Illuminate\\Foundation\\Configuration\\Exceptions;",
      "use Illuminate\\Foundation\\Configuration\\Middleware;",
      "",
      "return Application::configure(basePath: dirname(__DIR__))",
      "    ->withRouting(",
      "        web: __DIR__.'/../routes/web.php',",
      "        api: __DIR__.'/../routes/api.php',",
      "        commands: __DIR__.'/../routes/console.php',",
      "        health: '/up',",
      "    )",
      "    ->withMiddleware(function (Middleware $middleware): void {",
      "        //",
      "    })",
      "    ->withExceptions(function (Exceptions $exceptions): void {",
      "        //",
      "    })->create();",
    ]),
    "bootstrap/cache/.gitignore": lines([
      "*",
      "!.gitignore",
    ]),
    "bootstrap/providers.php": lines([
      "<?php",
      "",
      "return [",
      "    App\\Providers\\AppServiceProvider::class,",
      "];",
    ]),
    "config/app.php": lines([
      "<?php",
      "",
      "return [",
      "    'name' => env('APP_NAME', 'Laravel'),",
      "",
      "    'env' => env('APP_ENV', 'production'),",
      "",
      "    'debug' => (bool) env('APP_DEBUG', false),",
      "",
      "    'url' => env('APP_URL', 'http://localhost'),",
      "",
      "    'timezone' => 'UTC',",
      "",
      "    'locale' => env('APP_LOCALE', 'en'),",
      "",
      "    'fallback_locale' => env('APP_FALLBACK_LOCALE', 'en'),",
      "",
      "    'faker_locale' => env('APP_FAKER_LOCALE', 'en_US'),",
      "",
      "    'cipher' => 'AES-256-CBC',",
      "",
      "    'key' => env('APP_KEY'),",
      "",
      "    'previous_keys' => [",
      "        ...array_filter(",
      "            explode(',', env('APP_PREVIOUS_KEYS', ''))",
      "        ),",
      "    ],",
      "",
      "    'maintenance' => [",
      "        'driver' => env('APP_MAINTENANCE_DRIVER', 'file'),",
      "        'store' => env('APP_MAINTENANCE_STORE', 'database'),",
      "    ],",
      "];",
    ]),
    "config/auth.php": lines([
      "<?php",
      "",
      "return [",
      "    'defaults' => [",
      "        'guard' => env('AUTH_GUARD', 'web'),",
      "        'passwords' => env('AUTH_PASSWORD_BROKER', 'users'),",
      "    ],",
      "",
      "    'guards' => [",
      "        'web' => [",
      "            'driver' => 'session',",
      "            'provider' => 'users',",
      "        ],",
      "    ],",
      "",
      "    'providers' => [",
      "        'users' => [",
      "            'driver' => 'eloquent',",
      "            'model' => env('AUTH_MODEL', App\\Models\\User::class),",
      "        ],",
      "    ],",
      "",
      "    'passwords' => [",
      "        'users' => [",
      "            'provider' => 'users',",
      "            'table' => env('AUTH_PASSWORD_RESET_TOKEN_TABLE', 'password_reset_tokens'),",
      "            'expire' => 60,",
      "            'throttle' => 60,",
      "        ],",
      "    ],",
      "",
      "    'password_timeout' => env('AUTH_PASSWORD_TIMEOUT', 10800),",
      "];",
    ]),
    "config/cache.php": lines([
      "<?php",
      "",
      "use Illuminate\\Support\\Str;",
      "",
      "return [",
      "    'default' => env('CACHE_STORE', 'database'),",
      "",
      "    'stores' => [",
      "        'array' => [",
      "            'driver' => 'array',",
      "            'serialize' => false,",
      "        ],",
      "",
      "        'database' => [",
      "            'driver' => 'database',",
      "            'connection' => env('DB_CACHE_CONNECTION'),",
      "            'table' => env('DB_CACHE_TABLE', 'cache'),",
      "            'lock_connection' => env('DB_CACHE_LOCK_CONNECTION'),",
      "            'lock_table' => env('DB_CACHE_LOCK_TABLE', 'cache_locks'),",
      "        ],",
      "",
      "        'file' => [",
      "            'driver' => 'file',",
      "            'path' => storage_path('framework/cache/data'),",
      "            'lock_path' => storage_path('framework/cache/data'),",
      "        ],",
      "",
      "        'redis' => [",
      "            'driver' => 'redis',",
      "            'connection' => env('REDIS_CACHE_CONNECTION', 'cache'),",
      "            'lock_connection' => env('REDIS_CACHE_LOCK_CONNECTION', 'default'),",
      "        ],",
      "    ],",
      "",
      "    'prefix' => env('CACHE_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_cache_'),",
      "];",
    ]),
    "config/database.php": lines([
      "<?php",
      "",
      "use Illuminate\\Support\\Str;",
      "",
      "return [",
      "    'default' => env('DB_CONNECTION', 'sqlite'),",
      "",
      "    'connections' => [",
      "        'sqlite' => [",
      "            'driver' => 'sqlite',",
      "            'url' => env('DB_URL'),",
      "            'database' => env('DB_DATABASE', database_path('database.sqlite')),",
      "            'prefix' => '',",
      "            'foreign_key_constraints' => env('DB_FOREIGN_KEYS', true),",
      "            'busy_timeout' => null,",
      "            'journal_mode' => null,",
      "            'synchronous' => null,",
      "        ],",
      "",
      "        'mysql' => [",
      "            'driver' => 'mysql',",
      "            'url' => env('DB_URL'),",
      "            'host' => env('DB_HOST', '127.0.0.1'),",
      "            'port' => env('DB_PORT', '3306'),",
      "            'database' => env('DB_DATABASE', 'laravel'),",
      "            'username' => env('DB_USERNAME', 'root'),",
      "            'password' => env('DB_PASSWORD', ''),",
      "            'unix_socket' => env('DB_SOCKET', ''),",
      "            'charset' => env('DB_CHARSET', 'utf8mb4'),",
      "            'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),",
      "            'prefix' => '',",
      "            'prefix_indexes' => true,",
      "            'strict' => true,",
      "            'engine' => null,",
      "            'options' => extension_loaded('pdo_mysql') ? array_filter([",
      "                PDO::MYSQL_ATTR_SSL_CA => env('MYSQL_ATTR_SSL_CA'),",
      "            ]) : [],",
      "        ],",
      "",
      "        'pgsql' => [",
      "            'driver' => 'pgsql',",
      "            'url' => env('DB_URL'),",
      "            'host' => env('DB_HOST', '127.0.0.1'),",
      "            'port' => env('DB_PORT', '5432'),",
      "            'database' => env('DB_DATABASE', 'laravel'),",
      "            'username' => env('DB_USERNAME', 'root'),",
      "            'password' => env('DB_PASSWORD', ''),",
      "            'charset' => env('DB_CHARSET', 'utf8'),",
      "            'prefix' => '',",
      "            'prefix_indexes' => true,",
      "            'search_path' => 'public',",
      "            'sslmode' => 'prefer',",
      "        ],",
      "    ],",
      "",
      "    'migrations' => [",
      "        'table' => 'migrations',",
      "        'update_date_on_publish' => true,",
      "    ],",
      "",
      "    'redis' => [",
      "        'client' => env('REDIS_CLIENT', 'phpredis'),",
      "",
      "        'options' => [",
      "            'cluster' => env('REDIS_CLUSTER', 'redis'),",
      "            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),",
      "            'persistent' => env('REDIS_PERSISTENT', false),",
      "        ],",
      "",
      "        'default' => [",
      "            'url' => env('REDIS_URL'),",
      "            'host' => env('REDIS_HOST', '127.0.0.1'),",
      "            'username' => env('REDIS_USERNAME'),",
      "            'password' => env('REDIS_PASSWORD'),",
      "            'port' => env('REDIS_PORT', '6379'),",
      "            'database' => env('REDIS_DB', '0'),",
      "        ],",
      "",
      "        'cache' => [",
      "            'url' => env('REDIS_URL'),",
      "            'host' => env('REDIS_HOST', '127.0.0.1'),",
      "            'username' => env('REDIS_USERNAME'),",
      "            'password' => env('REDIS_PASSWORD'),",
      "            'port' => env('REDIS_PORT', '6379'),",
      "            'database' => env('REDIS_CACHE_DB', '1'),",
      "        ],",
      "    ],",
      "];",
    ]),
    "config/filesystems.php": lines([
      "<?php",
      "",
      "return [",
      "    'default' => env('FILESYSTEM_DISK', 'local'),",
      "",
      "    'disks' => [",
      "        'local' => [",
      "            'driver' => 'local',",
      "            'root' => storage_path('app/private'),",
      "            'serve' => true,",
      "            'throw' => false,",
      "        ],",
      "",
      "        'public' => [",
      "            'driver' => 'local',",
      "            'root' => storage_path('app/public'),",
      "            'url' => env('APP_URL').'/storage',",
      "            'visibility' => 'public',",
      "            'throw' => false,",
      "        ],",
      "    ],",
      "",
      "    'links' => [",
      "        public_path('storage') => storage_path('app/public'),",
      "    ],",
      "];",
    ]),
    "config/logging.php": lines([
      "<?php",
      "",
      "use Monolog\\Handler\\NullHandler;",
      "use Monolog\\Handler\\StreamHandler;",
      "use Monolog\\Handler\\SyslogUdpHandler;",
      "use Monolog\\Processor\\PsrLogMessageProcessor;",
      "",
      "return [",
      "    'default' => env('LOG_CHANNEL', 'stack'),",
      "",
      "    'deprecations' => [",
      "        'channel' => env('LOG_DEPRECATIONS_CHANNEL', 'null'),",
      "        'trace' => env('LOG_DEPRECATIONS_TRACE', false),",
      "    ],",
      "",
      "    'channels' => [",
      "        'stack' => [",
      "            'driver' => 'stack',",
      "            'channels' => explode(',', env('LOG_STACK', 'single')),",
      "            'ignore_exceptions' => false,",
      "        ],",
      "",
      "        'single' => [",
      "            'driver' => 'single',",
      "            'path' => storage_path('logs/laravel.log'),",
      "            'level' => env('LOG_LEVEL', 'debug'),",
      "            'replace_placeholders' => true,",
      "        ],",
      "",
      "        'daily' => [",
      "            'driver' => 'daily',",
      "            'path' => storage_path('logs/laravel.log'),",
      "            'level' => env('LOG_LEVEL', 'debug'),",
      "            'days' => env('LOG_DAILY_DAYS', 14),",
      "            'replace_placeholders' => true,",
      "        ],",
      "",
      "        'slack' => [",
      "            'driver' => 'slack',",
      "            'url' => env('LOG_SLACK_WEBHOOK_URL'),",
      "            'username' => env('LOG_SLACK_USERNAME', 'Laravel Log'),",
      "            'emoji' => env('LOG_SLACK_EMOJI', ':boom:'),",
      "            'level' => env('LOG_LEVEL', 'critical'),",
      "            'replace_placeholders' => true,",
      "        ],",
      "",
      "        'papertrail' => [",
      "            'driver' => 'monolog',",
      "            'level' => env('LOG_LEVEL', 'debug'),",
      "            'handler' => env('LOG_PAPERTRAIL_HANDLER', SyslogUdpHandler::class),",
      "            'handler_with' => [",
      "                'host' => env('PAPERTRAIL_URL'),",
      "                'port' => env('PAPERTRAIL_PORT'),",
      "                'connectionString' => 'tls://'.env('PAPERTRAIL_URL').':'.env('PAPERTRAIL_PORT'),",
      "            ],",
      "            'processors' => [PsrLogMessageProcessor::class],",
      "        ],",
      "",
      "        'stderr' => [",
      "            'driver' => 'monolog',",
      "            'level' => env('LOG_LEVEL', 'debug'),",
      "            'handler' => StreamHandler::class,",
      "            'handler_with' => [",
      "                'stream' => 'php://stderr',",
      "            ],",
      "            'formatter' => env('LOG_STDERR_FORMATTER'),",
      "            'processors' => [PsrLogMessageProcessor::class],",
      "        ],",
      "",
      "        'syslog' => [",
      "            'driver' => 'syslog',",
      "            'level' => env('LOG_LEVEL', 'debug'),",
      "            'facility' => env('LOG_SYSLOG_FACILITY', LOG_USER),",
      "            'replace_placeholders' => true,",
      "        ],",
      "",
      "        'errorlog' => [",
      "            'driver' => 'errorlog',",
      "            'level' => env('LOG_LEVEL', 'debug'),",
      "            'replace_placeholders' => true,",
      "        ],",
      "",
      "        'null' => [",
      "            'driver' => 'monolog',",
      "            'handler' => NullHandler::class,",
      "        ],",
      "",
      "        'emergency' => [",
      "            'path' => storage_path('logs/laravel.log'),",
      "        ],",
      "    ],",
      "];",
    ]),
    "config/mail.php": lines([
      "<?php",
      "",
      "return [",
      "    'default' => env('MAIL_MAILER', 'log'),",
      "",
      "    'mailers' => [",
      "        'smtp' => [",
      "            'transport' => 'smtp',",
      "            'scheme' => env('MAIL_SCHEME'),",
      "            'url' => env('MAIL_URL'),",
      "            'host' => env('MAIL_HOST', '127.0.0.1'),",
      "            'port' => env('MAIL_PORT', 2525),",
      "            'username' => env('MAIL_USERNAME'),",
      "            'password' => env('MAIL_PASSWORD'),",
      "            'timeout' => null,",
      "            'local_domain' => env('MAIL_EHLO_DOMAIN', parse_url(env('APP_URL', 'http://localhost'), PHP_URL_HOST)),",
      "        ],",
      "",
      "        'log' => [",
      "            'transport' => 'log',",
      "            'channel' => env('MAIL_LOG_CHANNEL'),",
      "        ],",
      "",
      "        'array' => [",
      "            'transport' => 'array',",
      "        ],",
      "",
      "        'failover' => [",
      "            'transport' => 'failover',",
      "            'mailers' => [",
      "                'smtp',",
      "                'log',",
      "            ],",
      "        ],",
      "    ],",
      "",
      "    'from' => [",
      "        'address' => env('MAIL_FROM_ADDRESS', 'hello@example.com'),",
      "        'name' => env('MAIL_FROM_NAME', 'Example'),",
      "    ],",
      "];",
    ]),
    "config/queue.php": lines([
      "<?php",
      "",
      "return [",
      "    'default' => env('QUEUE_CONNECTION', 'database'),",
      "",
      "    'connections' => [",
      "        'sync' => [",
      "            'driver' => 'sync',",
      "        ],",
      "",
      "        'database' => [",
      "            'driver' => 'database',",
      "            'connection' => env('DB_QUEUE_CONNECTION'),",
      "            'table' => env('DB_QUEUE_TABLE', 'jobs'),",
      "            'queue' => env('DB_QUEUE', 'default'),",
      "            'retry_after' => (int) env('DB_QUEUE_RETRY_AFTER', 90),",
      "            'after_commit' => false,",
      "        ],",
      "",
      "        'redis' => [",
      "            'driver' => 'redis',",
      "            'connection' => env('REDIS_QUEUE_CONNECTION', 'default'),",
      "            'queue' => env('REDIS_QUEUE', 'default'),",
      "            'retry_after' => (int) env('REDIS_QUEUE_RETRY_AFTER', 90),",
      "            'block_for' => null,",
      "            'after_commit' => false,",
      "        ],",
      "    ],",
      "",
      "    'batching' => [",
      "        'database' => env('DB_CONNECTION', 'sqlite'),",
      "        'table' => 'job_batches',",
      "    ],",
      "",
      "    'failed' => [",
      "        'driver' => env('QUEUE_FAILED_DRIVER', 'database-uuids'),",
      "        'database' => env('DB_CONNECTION', 'sqlite'),",
      "        'table' => 'failed_jobs',",
      "    ],",
      "];",
    ]),
    "config/services.php": lines([
      "<?php",
      "",
      "return [",
      "    'postmark' => [",
      "        'token' => env('POSTMARK_TOKEN'),",
      "    ],",
      "",
      "    'ses' => [",
      "        'key' => env('AWS_ACCESS_KEY_ID'),",
      "        'secret' => env('AWS_SECRET_ACCESS_KEY'),",
      "        'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),",
      "    ],",
      "",
      "    'resend' => [",
      "        'key' => env('RESEND_KEY'),",
      "    ],",
      "",
      "    'slack' => [",
      "        'notifications' => [",
      "            'bot_user_oauth_token' => env('SLACK_BOT_USER_OAUTH_TOKEN'),",
      "            'channel' => env('SLACK_BOT_USER_DEFAULT_CHANNEL'),",
      "        ],",
      "    ],",
      "];",
    ]),
    "config/session.php": lines([
      "<?php",
      "",
      "use Illuminate\\Support\\Str;",
      "",
      "return [",
      "    'driver' => env('SESSION_DRIVER', 'database'),",
      "",
      "    'lifetime' => (int) env('SESSION_LIFETIME', 120),",
      "",
      "    'expire_on_close' => env('SESSION_EXPIRE_ON_CLOSE', false),",
      "",
      "    'encrypt' => env('SESSION_ENCRYPT', false),",
      "",
      "    'files' => storage_path('framework/sessions'),",
      "",
      "    'connection' => env('SESSION_CONNECTION'),",
      "",
      "    'table' => env('SESSION_TABLE', 'sessions'),",
      "",
      "    'store' => env('SESSION_STORE'),",
      "",
      "    'lottery' => [2, 100],",
      "",
      "    'cookie' => env(",
      "        'SESSION_COOKIE',",
      "        Str::slug(env('APP_NAME', 'laravel'), '_').'_session'",
      "    ),",
      "",
      "    'path' => env('SESSION_PATH', '/'),",
      "",
      "    'domain' => env('SESSION_DOMAIN'),",
      "",
      "    'secure' => env('SESSION_SECURE_COOKIE'),",
      "",
      "    'http_only' => env('SESSION_HTTP_ONLY', true),",
      "",
      "    'same_site' => env('SESSION_SAME_SITE', 'lax'),",
      "",
      "    'partitioned' => env('SESSION_PARTITIONED_COOKIE', false),",
      "];",
    ]),
    "database/database.sqlite": "",
    "database/factories/UserFactory.php": lines([
      "<?php",
      "",
      "namespace Database\\Factories;",
      "",
      "use Illuminate\\Database\\Eloquent\\Factories\\Factory;",
      "use Illuminate\\Support\\Facades\\Hash;",
      "use Illuminate\\Support\\Str;",
      "",
      "/**",
      " * @extends \\Illuminate\\Database\\Eloquent\\Factories\\Factory<\\App\\Models\\User>",
      " */",
      "class UserFactory extends Factory",
      "{",
      "    /**",
      "     * The current password being used by the factory.",
      "     */",
      "    protected static ?string $password;",
      "",
      "    /**",
      "     * Define the model's default state.",
      "     *",
      "     * @return array<string, mixed>",
      "     */",
      "    public function definition(): array",
      "    {",
      "        return [",
      "            'name' => fake()->name(),",
      "            'email' => fake()->unique()->safeEmail(),",
      "            'email_verified_at' => now(),",
      "            'password' => static::$password ??= Hash::make('password'),",
      "            'remember_token' => Str::random(10),",
      "        ];",
      "    }",
      "",
      "    /**",
      "     * Indicate that the model's email address should be unverified.",
      "     */",
      "    public function unverified(): static",
      "    {",
      "        return $this->state(fn (array $attributes) => [",
      "            'email_verified_at' => null,",
      "        ]);",
      "    }",
      "}",
    ]),
    "database/migrations/0001_01_01_000000_create_users_table.php": lines([
      "<?php",
      "",
      "use Illuminate\\Database\\Migrations\\Migration;",
      "use Illuminate\\Database\\Schema\\Blueprint;",
      "use Illuminate\\Support\\Facades\\Schema;",
      "",
      "return new class extends Migration",
      "{",
      "    public function up(): void",
      "    {",
      "        Schema::create('users', function (Blueprint $table) {",
      "            $table->id();",
      "            $table->string('name');",
      "            $table->string('email')->unique();",
      "            $table->timestamp('email_verified_at')->nullable();",
      "            $table->string('password');",
      "            $table->rememberToken();",
      "            $table->timestamps();",
      "        });",
      "",
      "        Schema::create('password_reset_tokens', function (Blueprint $table) {",
      "            $table->string('email')->primary();",
      "            $table->string('token');",
      "            $table->timestamp('created_at')->nullable();",
      "        });",
      "",
      "        Schema::create('sessions', function (Blueprint $table) {",
      "            $table->string('id')->primary();",
      "            $table->foreignId('user_id')->nullable()->index();",
      "            $table->string('ip_address', 45)->nullable();",
      "            $table->text('user_agent')->nullable();",
      "            $table->longText('payload');",
      "            $table->integer('last_activity')->index();",
      "        });",
      "    }",
      "",
      "    public function down(): void",
      "    {",
      "        Schema::dropIfExists('users');",
      "        Schema::dropIfExists('password_reset_tokens');",
      "        Schema::dropIfExists('sessions');",
      "    }",
      "};",
    ]),
    "database/migrations/0001_01_01_000001_create_cache_table.php": lines([
      "<?php",
      "",
      "use Illuminate\\Database\\Migrations\\Migration;",
      "use Illuminate\\Database\\Schema\\Blueprint;",
      "use Illuminate\\Support\\Facades\\Schema;",
      "",
      "return new class extends Migration",
      "{",
      "    public function up(): void",
      "    {",
      "        Schema::create('cache', function (Blueprint $table) {",
      "            $table->string('key')->primary();",
      "            $table->mediumText('value');",
      "            $table->integer('expiration');",
      "        });",
      "",
      "        Schema::create('cache_locks', function (Blueprint $table) {",
      "            $table->string('key')->primary();",
      "            $table->string('owner');",
      "            $table->integer('expiration');",
      "        });",
      "    }",
      "",
      "    public function down(): void",
      "    {",
      "        Schema::dropIfExists('cache');",
      "        Schema::dropIfExists('cache_locks');",
      "    }",
      "};",
    ]),
    "database/migrations/0001_01_01_000002_create_jobs_table.php": lines([
      "<?php",
      "",
      "use Illuminate\\Database\\Migrations\\Migration;",
      "use Illuminate\\Database\\Schema\\Blueprint;",
      "use Illuminate\\Support\\Facades\\Schema;",
      "",
      "return new class extends Migration",
      "{",
      "    public function up(): void",
      "    {",
      "        Schema::create('jobs', function (Blueprint $table) {",
      "            $table->id();",
      "            $table->string('queue')->index();",
      "            $table->longText('payload');",
      "            $table->unsignedTinyInteger('attempts');",
      "            $table->unsignedInteger('reserved_at')->nullable();",
      "            $table->unsignedInteger('available_at');",
      "            $table->unsignedInteger('created_at');",
      "        });",
      "",
      "        Schema::create('job_batches', function (Blueprint $table) {",
      "            $table->string('id')->primary();",
      "            $table->string('name');",
      "            $table->integer('total_jobs');",
      "            $table->integer('pending_jobs');",
      "            $table->integer('failed_jobs');",
      "            $table->longText('failed_job_ids');",
      "            $table->mediumText('options')->nullable();",
      "            $table->integer('cancelled_at')->nullable();",
      "            $table->integer('created_at');",
      "            $table->integer('finished_at')->nullable();",
      "        });",
      "",
      "        Schema::create('failed_jobs', function (Blueprint $table) {",
      "            $table->id();",
      "            $table->string('uuid')->unique();",
      "            $table->text('connection');",
      "            $table->text('queue');",
      "            $table->longText('payload');",
      "            $table->longText('exception');",
      "            $table->timestamp('failed_at')->useCurrent();",
      "        });",
      "    }",
      "",
      "    public function down(): void",
      "    {",
      "        Schema::dropIfExists('jobs');",
      "        Schema::dropIfExists('job_batches');",
      "        Schema::dropIfExists('failed_jobs');",
      "    }",
      "};",
    ]),
    "database/seeders/DatabaseSeeder.php": lines([
      "<?php",
      "",
      "namespace Database\\Seeders;",
      "",
      "use App\\Models\\User;",
      "use Illuminate\\Database\\Seeder;",
      "",
      "class DatabaseSeeder extends Seeder",
      "{",
      "    public function run(): void",
      "    {",
      "        User::factory()->create([",
      "            'name' => 'Test User',",
      "            'email' => 'test@example.com',",
      "        ]);",
      "    }",
      "}",
    ]),
    "public/.htaccess": lines([
      "<IfModule mod_rewrite.c>",
      "    <IfModule mod_negotiation.c>",
      "        Options -MultiViews -Indexes",
      "    </IfModule>",
      "",
      "    RewriteEngine On",
      "",
      "    RewriteCond %{HTTP:Authorization} .",
      "    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]",
      "",
      "    RewriteCond %{REQUEST_FILENAME} !-d",
      "    RewriteCond %{REQUEST_URI} (.+)/$",
      "    RewriteRule ^ %1 [L,R=301]",
      "",
      "    RewriteCond %{REQUEST_FILENAME} !-d",
      "    RewriteCond %{REQUEST_FILENAME} !-f",
      "    RewriteRule ^ index.php [L]",
      "</IfModule>",
    ]),
    "public/index.php": lines([
      "<?php",
      "",
      "use Illuminate\\Http\\Request;",
      "",
      "define('LARAVEL_START', microtime(true));",
      "",
      "if (file_exists($maintenance = __DIR__.'/../storage/framework/maintenance.php')) {",
      "    require $maintenance;",
      "}",
      "",
      "require __DIR__.'/../vendor/autoload.php';",
      "",
      "/** @var \\Illuminate\\Foundation\\Application $app */",
      "$app = require_once __DIR__.'/../bootstrap/app.php';",
      "",
      "$app->handleRequest(Request::capture());",
    ]),
    "public/robots.txt": lines([
      "User-agent: *",
      "Disallow:",
    ]),
    "resources/css/app.css": lines([
      "@import 'tailwindcss';",
      "",
      ":root {",
      "  color: #172033;",
      "  background: #f7f8fb;",
      "  font-family:",
      "    Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;",
      "}",
      "",
      "* {",
      "  box-sizing: border-box;",
      "}",
      "",
      "body {",
      "  margin: 0;",
      "  min-width: 320px;",
      "  min-height: 100vh;",
      "}",
      "",
      "button, input, textarea, select {",
      "  font: inherit;",
      "}",
    ]),
    "resources/js/app.js": lines([
      "import './bootstrap';",
    ]),
    "resources/js/bootstrap.js": lines([
      "import axios from 'axios';",
      "",
      "window.axios = axios;",
      "window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';",
    ]),
    "resources/views/components/layouts/app.blade.php": lines([
      "<!doctype html>",
      "<html lang=\"{{ str_replace('_', '-', app()->getLocale()) }}\">",
      "  <head>",
      "    <meta charset=\"utf-8\">",
      "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
      "    <meta name=\"csrf-token\" content=\"{{ csrf_token() }}\">",
      "    <title>{{ $title ?? config('app.name') }}</title>",
      "    @vite(['resources/css/app.css', 'resources/js/app.js'])",
      "  </head>",
      "  <body class=\"bg-slate-50 text-slate-950 antialiased\">",
      "    <div class=\"min-h-screen\">",
      "      <header class=\"border-b border-slate-200 bg-white\">",
      "        <nav class=\"mx-auto flex max-w-6xl items-center justify-between px-6 py-4\">",
      "          <a class=\"text-base font-bold tracking-normal text-slate-950\" href=\"{{ route('home') }}\">",
      "            {{ config('app.name') }}",
      "          </a>",
      "          <a class=\"text-sm font-medium text-slate-600 hover:text-slate-950\" href=\"https://laravel.com/docs\" rel=\"noreferrer\" target=\"_blank\">",
      "            Docs",
      "          </a>",
      "        </nav>",
      "      </header>",
      "",
      "      <main class=\"mx-auto flex max-w-6xl flex-col gap-8 px-6 py-10\">",
      "        {{ $slot }}",
      "      </main>",
      "    </div>",
      "  </body>",
      "</html>",
    ]),
    "resources/views/pages/home.blade.php": lines([
      "<x-layouts.app :title=\"config('app.name')\">",
      "  <div class=\"grid gap-8 lg:grid-cols-[1fr_28rem] lg:items-start\">",
      "    <section>",
      "      <p class=\"text-sm font-semibold uppercase tracking-normal text-emerald-700\">Laravel framework template</p>",
      "      <h1 class=\"mt-3 max-w-3xl text-4xl font-bold text-slate-950 sm:text-5xl\">",
      "        {{ config('app.name') }}",
      "      </h1>",
      "      <p class=\"mt-4 max-w-2xl text-lg leading-8 text-slate-600\">",
      "        Start building with Laravel, Blade, Vite, Tailwind CSS, SQLite defaults, migrations, and a ready health-check API.",
      "      </p>",
      "",
      "      <div class=\"mt-8 grid max-w-2xl gap-3 sm:grid-cols-3\">",
      "        <div class=\"rounded-lg border border-slate-200 bg-white p-4 shadow-sm\">",
      "          <p class=\"text-sm font-semibold text-slate-950\">Backend</p>",
      "          <p class=\"mt-1 text-sm text-slate-500\">Laravel {{ app()->version() }}</p>",
      "        </div>",
      "        <div class=\"rounded-lg border border-slate-200 bg-white p-4 shadow-sm\">",
      "          <p class=\"text-sm font-semibold text-slate-950\">Frontend</p>",
      "          <p class=\"mt-1 text-sm text-slate-500\">Blade + Vite</p>",
      "        </div>",
      "        <div class=\"rounded-lg border border-slate-200 bg-white p-4 shadow-sm\">",
      "          <p class=\"text-sm font-semibold text-slate-950\">Database</p>",
      "          <p class=\"mt-1 text-sm text-slate-500\">SQLite ready</p>",
      "        </div>",
      "      </div>",
      "    </section>",
      "",
      "    <section class=\"w-full rounded-lg border border-slate-200 bg-white p-5 shadow-sm\">",
      "      <p class=\"text-sm font-medium text-slate-500\">API status</p>",
      "      <div class=\"mt-3 flex items-center gap-2\">",
      "        <span class=\"h-3 w-3 rounded-full bg-emerald-500\"></span>",
      "        <strong class=\"text-lg text-slate-950\">Ready</strong>",
      "      </div>",
      "      <p class=\"mt-2 text-sm leading-6 text-slate-500\">",
      "        Visit <code class=\"rounded bg-slate-100 px-1.5 py-0.5 text-slate-800\">/api/health</code> to confirm JSON responses.",
      "      </p>",
      "      <div class=\"mt-5 rounded-lg bg-slate-950 p-4 text-sm text-slate-100\">",
      "        <span class=\"text-emerald-300\">GET</span> /api/health",
      "      </div>",
      "    </section>",
      "  </div>",
      "</x-layouts.app>",
    ]),
    "routes/api.php": lines([
      "<?php",
      "",
      "use App\\Http\\Controllers\\HealthController;",
      "use Illuminate\\Support\\Facades\\Route;",
      "",
      "Route::get('/health', HealthController::class)->name('api.health');",
    ]),
    "routes/console.php": lines([
      "<?php",
      "",
      "use Illuminate\\Foundation\\Inspiring;",
      "use Illuminate\\Support\\Facades\\Artisan;",
      "",
      "Artisan::command('inspire', function () {",
      "    $this->comment(Inspiring::quote());",
      "})->purpose('Display an inspiring quote');",
    ]),
    "routes/web.php": lines([
      "<?php",
      "",
      "use Illuminate\\Support\\Facades\\Route;",
      "",
      "Route::view('/', 'pages.home')->name('home');",
    ]),
    "storage/app/.gitignore": lines([
      "*",
      "!public/",
      "!.gitignore",
    ]),
    "storage/app/public/.gitignore": lines([
      "*",
      "!.gitignore",
    ]),
    "storage/framework/cache/.gitignore": lines([
      "*",
      "!data/",
      "!.gitignore",
    ]),
    "storage/framework/cache/data/.gitignore": lines([
      "*",
      "!.gitignore",
    ]),
    "storage/framework/sessions/.gitignore": lines([
      "*",
      "!.gitignore",
    ]),
    "storage/framework/testing/.gitignore": lines([
      "*",
      "!.gitignore",
    ]),
    "storage/framework/views/.gitignore": lines([
      "*",
      "!.gitignore",
    ]),
    "storage/logs/.gitignore": lines([
      "*",
      "!.gitignore",
    ]),
    "tests/Feature/HealthTest.php": lines([
      "<?php",
      "",
      "namespace Tests\\Feature;",
      "",
      "use Tests\\TestCase;",
      "",
      "class HealthTest extends TestCase",
      "{",
      "    public function test_health_endpoint_returns_ok(): void",
      "    {",
      "        $response = $this->getJson('/api/health');",
      "",
      "        $response->assertOk()",
      "            ->assertJson([",
      "                'status' => 'ok',",
      "            ]);",
      "    }",
      "",
      "    public function test_home_page_loads(): void",
      "    {",
      "        $this->get('/')",
      "            ->assertOk()",
      "            ->assertSee(config('app.name'));",
      "    }",
      "}",
    ]),
    "tests/TestCase.php": lines([
      "<?php",
      "",
      "namespace Tests;",
      "",
      "use Illuminate\\Foundation\\Testing\\TestCase as BaseTestCase;",
      "",
      "abstract class TestCase extends BaseTestCase",
      "{",
      "    //",
      "}",
    ]),
    "tests/Unit/ExampleTest.php": lines([
      "<?php",
      "",
      "namespace Tests\\Unit;",
      "",
      "use PHPUnit\\Framework\\TestCase;",
      "",
      "class ExampleTest extends TestCase",
      "{",
      "    public function test_that_true_is_true(): void",
      "    {",
      "        $this->assertTrue(true);",
      "    }",
      "}",
    ]),
  };

  return { directories, files };
}

function envString(value) {
  return '"' + value.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

function json(value) {
  return JSON.stringify(value, null, 2) + "\n";
}

function lines(value) {
  return value.join("\n") + "\n";
}

function toTitle(value) {
  return value
    .split(/[-_.\s]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
